version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:management"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
  order_app:
    build:
      context: order_app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
      - rabbitmq

  promo_app:
    build:
      context: promo_app
      dockerfile: Dockerfile
    ports:
      - "81:81"
    depends_on:
      - rabbitmq
      - order_app

  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: max@max.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data: