global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'order_app'
    static_configs:
      - targets: ['order_app:80']
  - job_name: 'promo_app'
    static_configs:
      - targets: ['promo_app:81']