name: CI/CD pipline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push-to-dh:
    name: Build and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker promo_app image
        run: |
          docker build ./promo_app -f ./promo_app/Dockerfile --tag mmjax/microservices-promocode:latest


      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push promo_app service image
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/microservices-promocode:latest
  build-and-push-to-yc:
    name: Build and push to YaCloud Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build ./order_app -f ./order_app/Dockerfile --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/microservices-order:latest

      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}

      - name: Push tag YC Registry
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/microservices-order:latest
  
